# Generated by Django 5.1.15 on 2026-07-06 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='herosection',
            options={'ordering': ['-updated_at'], 'verbose_name': 'Hero Section', 'verbose_name_plural': 'Hero Sections'},
        ),
    ]
