# Generated by Django 5.1.15 on 2026-07-06 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mission', models.TextField(blank=True)),
                ('vision', models.TextField(blank=True)),
                ('story', models.TextField(blank=True)),
                ('ceo_message', models.TextField(blank=True)),
                ('ceo_name', models.CharField(blank=True, max_length=200)),
                ('ceo_title', models.CharField(blank=True, max_length=200)),
                ('ceo_image', models.ImageField(blank=True, null=True, upload_to='about/')),
                ('is_published', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'About Content',
                'verbose_name_plural': 'About Content',
            },
        ),
    ]
